const products=[
{id:1,name:"Magnetic Cable Clips",cat:"Desk",price:19.99,image:"https://cf.cjdropshipping.com/17174592/2406040438510321900.jpg",desc:"Keep charging cables tidy and right where you need them. 6-piece magnetic-style cable organizer set.",supplierCost:"$0.05–$8.45",supplier:"CJdropshipping",source:"https://cjdropshipping.com/product/magnetic-cable-clip-under-desk-cable-management-adjustable-cord-holder-wire-organizer-and-cable-management-wire-keeper-p-1763402968205897728.html"},
{id:2,name:"Motion Sensor Night Light",cat:"Home",price:24.99,image:"https://cf.cjdropshipping.com/17109792/2403210555360324500.jpg",desc:"Rechargeable motion-sensing light with adjustable brightness and multiple color temperatures.",supplierCost:"$2.00–$15.00",supplier:"CJdropshipping",source:"https://cjdropshipping.com/product/new-style-smart-human-body-induction-motion-sensor-led-night-light-for-home-bed-kitchen-cabinet-wardrobe-wall-lamp-p-1714574022232510464.html"},
{id:3,name:"Adjustable Car Phone Mount",cat:"Auto",price:29.99,image:"https://cf.cjdropshipping.com/fecb2fd5-d8db-441c-87e6-ead7a7ec2782.jpg",desc:"360° adjustable windshield mount designed for phones between 2.3 and 3.2 inches wide.",supplierCost:"$13.78",supplier:"CJdropshipping",source:"https://cjdropshipping.com/product/windshield-car-phone-holder-universal-in-car-cellphone-holder-stand-adjustable-phone-suction-cup-holder-car-mount-phone-stand-p-7C59DE5B-A511-4920-88A8-C808B21476EE.html"},
{id:4,name:"Car Seat Gap Organizer",cat:"Auto",price:34.99,image:"https://cc-west-usa.oss-us-west-1.aliyuncs.com/b4d1f0de-3090-412d-9b47-6726784baf11.png",desc:"Leather-style organizer that fills the seat-to-console gap for keys, phones, sunglasses, and other small items.",supplierCost:"$4.34–$8.46",supplier:"CJdropshipping",source:"https://cjdropshipping.com/product/car-seat-gap-filler-organizer-car-seat-console-organizer-for-keys-phones-and-sunglasses-p-1803978693954916352.html"},
{id:5,name:"Travel Electronics Organizer",cat:"Travel",price:29.99,image:"https://cc-west-usa.oss-accelerate.aliyuncs.com/96f09d38-911c-44f9-928f-0b5e6dbd5f36.jpg",desc:"Double-layer cable and electronics case with mesh pockets, elastic loops, and adjustable dividers.",supplierCost:"$11.94",supplier:"CJdropshipping",source:"https://www.cjdropshipping.com/product/electronics-organizer-travel-cable-organizer-bag-waterproof-portable-digital-storage-bag-electronic-accessories-case-cable-charger-organizer-case-multifunctional-waterproof-storage-bag-p-1646726512265547776.html"},
{id:6,name:"Rechargeable Misting Fan",cat:"Everyday",price:39.99,image:"https://oss-cf.cjdropshipping.com/product/2025/05/09/03/39b25247-a78a-4f8b-b274-d6135ea65ae0_trans.jpeg",desc:"Rechargeable desktop fan with 3 speeds, 180° rotation, ambient light, and a 550ml misting tank.",supplierCost:"$6.86",supplier:"CJdropshipping",source:"https://sp-test.cjdropshipping.com/product/portable-fan-portable-mini-humidifier-fan-water-spraying-fan-rechargeable-cooler-air-adjustment-fan-for-hot-weather-p-2505090357211620800.html"},
{id:7,name:"Smart Mug Warmer",cat:"Home",price:29.99,image:"https://oss-cf.cjdropshipping.com/product/2026/04/23/06/0ab7acda-ba25-4020-af5e-58a74b08ad67_trans.jpeg",desc:"2-in-1 cup warmer with three temperature settings and a U.S.-standard option.",supplierCost:"$4.70–$5.03",supplier:"CJdropshipping",source:"https://cjdropshipping.com/product/mug-warmer-electric-cup-warmer-fastest-heating-cup-heater-with-temperature-display-for-coffee-milk-tea-fan-warmer-in-winter-a-home-and-office-heating-gadget-p-2604230646211624000.html"}
];
let cart=JSON.parse(localStorage.getItem("sf_cart")||"[]");
const cats=["All",...new Set(products.map(p=>p.cat))];
function renderFilters(){filters.innerHTML=cats.map((c,i)=>`<button class="${i===0?'active':''}" onclick="filter('${c}',this)">${c}</button>`).join("")}
function render(list=products){productsEl.innerHTML=list.map(p=>`<article class="product"><div class="pic"><img src="${p.image}" alt="${p.name}" loading="lazy"></div><div class="body"><span class="tag">${p.cat}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="buy"><b>$${p.price.toFixed(2)}</b><button onclick="add(${p.id})">Add</button></div></div></article>`).join("")}
function filter(cat,el){document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));el.classList.add("active");render(cat==="All"?products:products.filter(p=>p.cat===cat))}
function add(id){cart.push(id);save();openCart()}
function addHero(){add(1)}
function save(){localStorage.setItem("sf_cart",JSON.stringify(cart));updateCart()}
function updateCart(){cartCount.textContent=cart.length;let rows=cart.map(id=>products.find(p=>p.id===id)).filter(Boolean);cartItems.innerHTML=rows.length?rows.map((p,i)=>`<div class="cartRow"><img src="${p.image}" alt=""><div><b>${p.name}</b><div>$${p.price.toFixed(2)}</div><div class="qty"><button onclick="removeOne(${i})">−</button><small>1</small><button onclick="add(${p.id})">+</button></div></div></div>`).join(""):`<p>Your cart is empty.</p>`;total.textContent="$"+rows.reduce((s,p)=>s+p.price,0).toFixed(2)}
function removeOne(i){cart.splice(i,1);save()}
function openCart(){overlay.classList.add("open");updateCart()}
function closeCart(e){if(!e||e.target===overlay)overlay.classList.remove("open")}
function checkout(){alert("Demo checkout: connect Stripe, Shopify, or another payment provider to accept live payments.")}
function runAI(){aiResult.textContent=" Scan complete — 7 supplier products reviewed; pricing and shipping still need final validation before launch."}
const productsEl=document.getElementById("products"),filters=document.getElementById("filters"),cartCount=document.getElementById("cartCount"),overlay=document.getElementById("overlay"),cartItems=document.getElementById("cartItems"),total=document.getElementById("total"),aiResult=document.getElementById("aiResult");
renderFilters();render();updateCart();
